version: '3'
services:
  wallet:
    build:
      build:
        context: .
        args:
          REPOSITORY: 'https://github.com/Crave-Project/Crave-NG'
          REF: master
    restart: always
    ports:
      - '48882:48882'
      - '48883:48883'
    command:
      - '-rpcuser=crave-wallet'
      - '-rpcpassword=eisbd4hq'
      - '-server=1'
      - '-listen=0'
    volumes:
      - './wallet/:/home/crave/'
  masternode:
    build:
      build:
        context: .
        args:
          REPOSITORY: 'https://github.com/Crave-Project/Crave-NG'
          REF: master
    restart: always
    ports:
      - '48882:48882'
      - '48883:48883'
    command:
      - '-rpcuser=crave-mn01'
      - '-rpcpassword=eisbd4hq'
      - '-rpcallowip=::/0'
      - '-server=0'
      - '-listen=1'
      - '-masternode=1'
      - '-masternodeprivkey=YourMasternodePrivKey'
    volumes:
      - './masternode/:/home/crave/'
